services:
  frontend:
    container_name: crfpe_athena
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://crfpe_protesto_bknd:8000
      - FASTAPI_BASE_URL=http://crfpe_protesto_bknd:8000
      - FAST_LOGIN_PATH=/auth/login
      - JWT_COOKIE_NAME=access_token
      - JWT_COOKIE_MAX_AGE=3600      
    networks:
      - crfpe_protesto_network

networks:
  crfpe_protesto_network:
    external: true
